[build]
  functions = ".functions"

[context.production]
  publish = "/_site"

[context.deploy-preview]
  publish = "/_site"

[dev]
  port = 8888
  publish = "/_site"

[[headers]]
  for = "/rss"
  [headers.values]
    Content-Type = "text/xml"

[[redirects]]
  from = "/api/get-feed"
  to = "/.netlify/functions/get-feed"
  status = 200