<script src="https://giscus.app/client.js"
        data-repo="robertz/kdfe-ssg"
        data-repo-id="R_kgDOK8F-Yw"
        data-category="Comments"
        data-category-id="DIC_kwDOK8F-Y84CcVjP"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="dark"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>